services:
    tl_user.registerclient.form:
        class: TL\UserBundle\Form\RegisterClientForm
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: tl_userbundle_registerclientform }
