tl_user:
    resource: "@TLUserBundle/Resources/config/routing.yml"
    prefix:   /

tl_main:
    resource: "@TLMainBundle/Resources/config/routing.yml"
    prefix:   /



# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
